/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import clases.Dibujo2;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author erwin
 */
public class frmPrincipal2 extends javax.swing.JFrame {
    Dibujo2 dib;
    int[][] mat;
    
    /**
     * Creates new form frmPrincipal2
     */
    public frmPrincipal2() {
        initComponents();
        dib = new Dibujo2(jpLienzo.getWidth(), jpLienzo.getHeight());
        mat = new int[8][12];
        for (int i=0;i<8;i++){
            for (int j=0;j<12;j++){
                mat[i][j] = 0;
            }
        }
        
        mat[2][6] = 1;
        //mat[2][3] = 1;
        //mat[2][4] = 1;
        
        /*
        mat[5][2] = 2;
        mat[5][3] = 2;
        mat[5][4] = 2;
        mat[6][4] = 2;
        */
        this.jpLienzo.add(dib);
        
        dib.setMat(mat);
        dib.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpLienzo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jpLienzo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpLienzoLayout = new javax.swing.GroupLayout(jpLienzo);
        jpLienzo.setLayout(jpLienzoLayout);
        jpLienzoLayout.setHorizontalGroup(
            jpLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        jpLienzoLayout.setVerticalGroup(
            jpLienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpLienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            JOptionPane.showMessageDialog(this,"Hola Mundo");
        }
        
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_DOWN:
                for (int j=10;j>0;j--){
                    for (int i=0;i<8;i++){
                        if (mat[i][j] == 1 && mat[i][j+1] == 0){
                            mat[i][j] = 0;
                            mat[i][j+1] = 1;
                        }
                    }
                }
                
                dib.setMat(mat);
                dib.repaint();
                break;
            case KeyEvent.VK_UP:
                for (int j=11;j>0;j--){
                    for (int i=0;i<8;i++){
                        if (mat[i][j] == 1 && mat[i][j-1] == 0){
                            mat[i][j] = 0;
                            mat[i][j-1] = 2;
                        }
                        
                        if (mat[i][j] == 2){
                            mat[i][j] = 1;
                        }
                    }
                }
                
                
                dib.setMat(mat);
                dib.repaint();
                //JOptionPane.showMessageDialog(this,"Tecla Arriba");
                break;
            case KeyEvent.VK_LEFT:
                for (int j=0;j<12;j++){
                    for (int i=1;i<8;i++){
                        if (mat[i][j] == 1 && mat[i-1][j] == 0){
                            mat[i][j] = 0;
                            mat[i-1][j] = 1;
                        }
                    }
                }
                
                dib.setMat(mat);
                dib.repaint();
                break;
            case KeyEvent.VK_RIGHT:
                for (int j=0;j<12;j++){
                    for (int i=6;i>=0;i--){
                        if (mat[i][j] == 1 && mat[i+1][j] == 0){
                            mat[i][j] = 0;
                            mat[i+1][j] = 1;
                        }
                    }
                }
                
                dib.setMat(mat);
                dib.repaint();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpLienzo;
    // End of variables declaration//GEN-END:variables
}
